### ISSUE TITLE
DB Snapshot Not Found Error

### ISSUE THREAD

**Issue by ajmalblp** [aws-samples/rds-snapshot-export-to-s3-pipeline#10]
Throws DB Snapshot not found error even though snapshot is available.

```
[ERROR] DBSnapshotNotFoundFault: An error occurred (DBSnapshotNotFound) when calling the StartExportTask operation: Could not find snapshot with name rds:org-dev-pg-shared-euc1-2021-05-23-03-36
Traceback (most recent call last):
  File "/var/task/main.py", line 44, in handler
    response = boto3.client("rds").start_export_task(
  File "/var/runtime/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
```

**Comment by ajmalblp** [comment]
I found the reason for the issue. I will update after fixing it locally.

**Comment by michaelmoussa** [comment]
Hi @ajmalblp. Were you able to solve the issue, or do you need further help?

**Comment by ajmal-bash** [comment]
Hi @michaelmoussa , I was working with Amazon Aurora and the code needs minor modification to work as expected.
I have made the necessary changes and created a pull request #12.
