### ISSUE TITLE
[ERROR] ClientError: An error occurred (InvalidParameterValue) when calling the StartExportTask operation: The parameter ExportTaskIdentifier is not a valid identifier. Identifiers must begin with a letter; must contain only ASCII letters, digits, and hyphens; and must not end with a hyphen or contain two consecutive hyphens.

### ISSUE THREAD

**Issue by sandyverden** [aws-samples/rds-snapshot-export-to-s3-pipeline#2]
Hello, 

i have follow the instruction to install rds-snapshot-export-to-s3-pipeline but lambda function not working with error 

[ERROR] ClientError: An error occurred (InvalidParameterValue) when calling the StartExportTask operation: The parameter ExportTaskIdentifier is not a valid identifier. Identifiers must begin with a letter; must contain only ASCII letters, digits, and hyphens; and must not end with a hyphen or contain two consecutive hyphens.
Traceback (most recent call last):
  File "/var/task/main.py", line 44, in handler
    response = boto3.client("rds").start_export_task(
  File "/var/runtime/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 626, in _make_api_call
    raise error_class(parsed_response, operation_name)

**Comment by sandyverden** [comment]
i think it's because singapore region doesn't support export to s3
